# section Repository contains all data regarding the repository that contains
# the site/blog issues.
[Repository]
# Users defines all users whose issues will be imported into the blog
# the first user must be the owner of the blog repository
# all usernames are login names for github
Users = ["dbriemann"]
# Name is just the name of the repository containing the blog issues/articles
Name = "blog"

# section Site contains all data that will be used in the statically generated html.
[Site]
Title = "Of Unproven Words And Code"
Author = "David Linus Briemann"
OneLineDesc = "A blog by David Linus Briemann, professional software engineer and hobby game dev"
Twitter = "Raging_Dave"
Mail = "ragingdave@mailbox.org"
# in the theme folder there is a theme.toml which specifies theme specific pages
Theme = "default"

# section custom allows to pass custom data into the glyph templating process.
[Custom]
# for example:
# MyPets = ["Tom", "Jerry"]

